### PR TITLE
Add dockerBoi to list of services

### PR DESCRIPTION
**Pull request by hulthe**
ooga booga

### CODE REVIEW

**Review by ViddeM — APPROVED** [review]
I guess this might work (lgtm?) // Someone who doesn't know the code.
Hope prod likes it 👍🏿

**Review by rosengrenen — APPROVED** [review]
lmao

**Review by Hoidi — APPROVED** [review]
Worked on my machine

**Comment by hulthe** [comment]
@digit pls merge

**Comment by Hoidi** [comment]
how it this not merged already? It's been up for 7 minutes smh

**Comment by hulthe** [comment]
ikr, totally unreasonable
digit needs to enable automerging

**Pull request merged**
