### PR TITLE
Specify which version of FA to use in README

### PR DESCRIPTION
**Pull request by Hoidi**

### CODE REVIEW

**Review by ericlp — APPROVED** [review]
This is very reasonable, i like this as much as tree-fiddy :ok_hand:

**Review by 89netraM — APPROVED** [review]

**Comment by Hoidi** [comment]
@cthit/digit merge?

**Comment by 89netraM** [comment]
I don't know exactly how this sholud be done. I'm used to having the one who submitted the PR perform the merge. Do you have the rights to merge? Should digIT be the ones to perform all merges?

**Comment by Hoidi** [comment]
I don't have the access rights to perform the merge :( Doesn't really matter who merges tbh

**Comment by 89netraM** [comment]
Okay. Then I know. Thank you!

**Pull request merged**
