### PR TITLE
Add IT merch shop

### PR DESCRIPTION
**Pull request by ericlp**

### CODE REVIEW

**Comment by Hoidi** [comment]
wow @ericlp jag hade ju tänkt fixa detta idag 😁 Too slow I guess

**Review by Hoidi — APPROVED** [review]
Hot

**Comment by Hoidi** [comment]
Oh man I don't feel so good @ericlp 
image

**Comment by ericlp** [comment]
Wat wat

**Comment by Hoidi** [comment]
What about the icon?

If I remeber correctly you have to use FA 4.7 (https://fontawesome.com/v4.7/icons/)

**Comment by Hoidi** [comment]
@cthit/digit

**Review by 89netraM — APPROVED** [review]
Nice 👍

**Pull request merged**
